### ISSUE TITLE
Please provide a license agreement

### ISSUE THREAD

**Issue by smsiebe** [ngageoint/geoevents#2]
Please add a clear license agreement, preferably one that is a standard OSS license.

**Comment by bradh** [comment]
This would be much appreciated. The current wording in the README.md leaves quite a lot unsaid, and license compatibility with other Free and Open Source Software is uncertain.

**Comment by ckras34** [comment]
Please understand this is not a template task when dealing with US government works as noted in this OSI FAQ section. 

http://opensource.org/faq#public-domain

Thanks for the notes.  We’ll see what we can do and circle back soon.

**Comment by ckras34** [comment]
Open source license compatibility issues should be minimal because a public domain work is not a copyright license per se—it’s the absence of one.  However, it has the same practical effect of a highly permissive open source license.  As Brian noted, you can blend the software by noting the public domain parts. This was stated with "combine with other software" and "other stipulations" in our notice.  

The notice clearly states that this work can be used by anyone for any purpose.  We only ask that you cite our work.  You can download the software, blend it with your own, and try to form a company with it.  It doesn't get much freer than that.  The next several software packages will be released under standard copyright-based licenses such as MIT and Apache 2.0.  If these standard licenses create a greater sense of community than public domain notices, then we’ll adjust accordingly in the future, if possible under contract and circumstances.

**Comment by bradh** [comment]
My concern is that the "cite our work" part requires legal review. That could (requires legal review) be equivalent to the old BSD advertisement clause, which makes it incompatible with many licenses, including the GPL.

I recognise the desire for recognition, but a standard (OSI) license (or explicit public domain without "extra" clauses) would avoid the need for legal review and any uncertainty.

**Comment by ckras34** [comment]
Public domain dedication notices come in many flavors.

http://www.nist.gov/el/softdisclaimer.cfm

 You're applying copyright-based terms to a non-copyright situation.  OSI deals in copyright-based licenses not waivers or notices.

**Comment by smsiebe** [comment]
So, if work produced under contract does not have a copyright unless a
contractor requests to do so in writing (
https://acquisition.gov/far/current/html/Subpart%2027_4.html), and the
government can't publicly release those non-copyright works under contract
(again, in the FAR), can't the COR request a contractor simply make a
written request to copyright the material with guarantees that it will be
released publicly under a specific OSI license?  In which case, the
contract would simply need to submit a form letter to the COR (fill in the
blanks for the license type, the agreed upon location for dissemination,
etc) and any "legal" be the concerns of the government, which of course
shouldn't be a concern, as they're the ones requesting the contractor do
this.  Then, who cares about who holds the copy"left", it's been released.

S

**Comment by ckras34** [comment]
As stated above, we can and will pick OSI licenses when the circumstances align. Applying hypothetical workflows to this situation does not change the backstory of this case.  We've declared this a public domain work and it has no restrictions.  In the spirit of compromise, we made the citation statement optional.

**Comment by bradh** [comment]
Thanks for the change at https://github.com/ngageoint/geoevents/commit/316dd3bd8d7e5b4cfa0ecc8b1b16b4dc64333c69 - resolves my concerns.
